cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'

urlpatterns = [
    path('detail', views.cart_detail, name='cart_detail'),
    path('add_list/<int:product_id>',views.cart_add_list,name='cart_add_list'),
    path('add/<int:product_id>',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove')
]

iTech/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('',include('shop.urls', namespace='shop')),
    path('cart/',include('cart.urls',namespace='cart')),
    # User Management
    
    path('payment/',include('payment.urls',namespace='payment')),
    path('orders/',include('orders.urls',namespace='orders')),
]

orders/urls.py
from django.urls import path
from .import views

app_name = 'orders'
urlpatterns = [
    path('create/',views.order_create,name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf,name='admin_order_pdf'),

]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .import views
from shop.views import SearchResultsListView

app_name = 'shop'

urlpatterns = [
    path('store/',views.product_store,name='product_store'),
    path('',views.product_list,name='product_list'),
    path('search/',SearchResultsListView.as_view(),name='search_results'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),   
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name= 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank = True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id,self.slug])
    
        
    

shop/views.py
import django
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product
from .recommender import Recommender
from django.views.generic import ListView
from django.db.models import Q

# Create your views here.
def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)
    if category_slug:
        category = get_object_or_404(Category,slug = category_slug)
        products = products.filter(category=category)
    return render(request,'shop/product/list.html',{'category':category,'categories':categories,'products':products})

def product_detail(request,id,slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product],4)
    return render(request,'shop/product/detail.html',{'product':product,'cart_product_form':cart_product_form,'recommended_products':recommended_products})

def base_view(request):
    categories = Category.objects.all()
    return render(request,'shop/base.html',{'categories':categories})

def product_store(request):
    categories = Category.objects.all()
    min_price = request.GET.get('min_price',0)
    max_price = request.GET.get('max_price',10000000000)
    products = Product.objects.filter(price__range=(min_price,max_price))
    return render(request,'shop/product/store.html',{'categories':categories,'products':products})

class SearchResultsListView(ListView):
    model = Product
    context_object_name = 'result'
    template_name = 'shop/product/search_results.html'
    def get_queryset(self):
       query = self.request.GET.get('q')
       return Product.objects.filter(
        Q(name__icontains=query))
    
    

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>{% block title %}iTech- Gadgets Store{% endblock title %}</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'bootstrap.min.css' %}"/>

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href="{% static 'slick.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'slick-theme.css' %}"/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'nouislider.min.css' %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'font-awesome.min.css' %}">
		<script src="https://use.fontawesome.com/99d105783f.js"></script>

		<!-- Custom stlylesheet -->

		
        <link type="text/css" href = "{% static 'base.css' %}" rel="stylesheet">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
        <body>
		<!-- /HEADER -->
        <header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +977-1234567890</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> itech@emai.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i> Shantinagar, Kathmandu</a></li>
					</ul>
					<ul class="header-links pull-right">
						<li><a href="#"><i class="fa fa-dollar"></i> NRS</a></li>
						{% if user.is_authenticated %}
							<li><a href="accounts/logout"><i class="fa fa-user-o"></i>Logout</a></li>
						{% else %}
							<li><a href="accounts/login"><i class="fa fa-user-o"></i>Login</a></li>
							<li><a href="accounts/signup"><i class="fa fa-user-o"></i>Sign Up</a></li>
						{% endif %}
						
					</ul>
				</div>
			</div>
        </header>
        <!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="#" class="logo">
									{% comment %} <img src="./img/logo.png" alt=""> {% endcomment %}
                                    iTech
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form action = "{% url 'shop:search_results' %}" method="get">
									<select class="input-select">
										<option value="0">All Categories</option>
                                        {% for category in categories %}
                                            <option value="{{category.name}}"><a href = "{{category.get_absolute_url}}">{{category.name}}</a></option>
                                        {% endfor %}				
									</select>
									<input name = "q" class="input" placeholder="Search here">
									<button type="submit" class="search-btn">Search</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">

							<div class="header-ctn">
								<!-- Cart -->
								<div class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-shopping-cart"></i>
										<span>Your Cart</span>
										{% with total_items=cart|length%}
											{% if total_items > 0 %}
												<div class = "qty">{{total_items}}</div>
											{% endif %}
										{% endwith %}
									</a>
									<div class="cart-dropdown">
										<div class="cart-summary">
											<small> {{cart|length}} selected</small>
                        					<h5>NRs {{cart.get_total_price}}</h5>
										</div>
										<div class="cart-btns">
											<a href="{% url 'cart:cart_detail' %}">View Cart</a>
											<a href="{% url 'orders:order_create' %}">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
										</div>
									</div>
								</div>
								<!-- /Cart -->
								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
        <!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="{% url 'shop:product_list'%}">Home</a></li>
						<li><a href="{% url 'shop:product_store'%}">Store</a></li>
                        {% for c in categories %}
                        <li {% if category.slug == c.slug %} class="selected"{% endif %}>
                          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                        </li>
                      {% endfor %}
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->
        <div class = "section">
            {% block content %}
            {% endblock content %}
        </div>
		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

			<!-- /MAIN HEADER -->
			<!-- /TOP HEADER -->
        <!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
    </body>
</html>
    


{% comment %} <!DOCTYPE html>
<html>
<head>
    <meta charset = "utf-8">
    <title>{% block title %}iTech{% endblock title %}</title>
    <link href = "{% static 'base.css' %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href = "/" class = "logo">iTech</a>
    </div>
    <div id = "subheader">
        <div class = "cart">
            {% with total_items=cart|length%}
                {% if total_items > 0 %}
                    Your cart:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{total_items}} item{{total_items|pluralize}},
                        NRs {{cart.get_total_price}}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id =  "content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html> {% endcomment %}