cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'

urlpatterns = [
    path('detail', views.cart_detail, name='cart_detail'),
    path('add_list/<int:product_id>',views.cart_add_list,name='cart_add_list'),
    path('add/<int:product_id>',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove')
]

iTech/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('',include('shop.urls', namespace='shop')),
    path('cart/',include('cart.urls',namespace='cart')),
    # User Management
    
    path('payment/',include('payment.urls',namespace='payment')),
    path('orders/',include('orders.urls',namespace='orders')),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .import views
from shop.views import SearchResultsListView

app_name = 'shop'

urlpatterns = [
    path('store/',views.product_store,name='product_store'),
    path('',views.product_list,name='product_list'),
    path('search/',SearchResultsListView.as_view(),name='search_results'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),   
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name= 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank = True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id,self.slug])
    
        
    

shop/views.py
import django
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product
from .recommender import Recommender
from django.views.generic import ListView
from django.db.models import Q

# Create your views here.
def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)
    if category_slug:
        category = get_object_or_404(Category,slug = category_slug)
        products = products.filter(category=category)
    return render(request,'shop/product/list.html',{'category':category,'categories':categories,'products':products})

def product_detail(request,id,slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product],4)
    return render(request,'shop/product/detail.html',{'product':product,'cart_product_form':cart_product_form,'recommended_products':recommended_products})

def base_view(request):
    categories = Category.objects.all()
    return render(request,'shop/base.html',{'categories':categories})

def product_store(request):
    categories = Category.objects.all()
    min_price = request.GET.get('min_price',0)
    max_price = request.GET.get('max_price',10000000000)
    products = Product.objects.filter(price__range=(min_price,max_price))
    return render(request,'shop/product/store.html',{'categories':categories,'products':products})

class SearchResultsListView(ListView):
    model = Product
    context_object_name = 'result'
    template_name = 'shop/product/search_results.html'
    def get_queryset(self):
       query = self.request.GET.get('q')
       return Product.objects.filter(
        Q(name__icontains=query))
    
    

templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{{product.name}}{% endblock title %}
{% block content %}
  <div class = "container">
    <div class = "row">
      <!-- Product main img -->
					<div class="col-md-5 col-md-push-2">
						<div id="product-main-img">
							<div class="product-preview">
								<img src="{{product.image.url}}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{{product.image.url}}" alt="{{product.name}}">
							</div>
						</div>
					</div>
					<!-- /Product main img -->
          					<!-- Product thumb imgs -->
					<div class="col-md-2  col-md-pull-5">
						<div id="product-imgs">
							<div class="product-preview">
								<img src="{{product.image.url}}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{{product.image.url}}" alt="{{product.name}}">
							</div>
						</div>
					</div>
					<!-- /Product thumb imgs -->
          					<!-- Product details -->
					<div class="col-md-5">
						<div class="product-details">
							<h2 class="product-name">{{product.name}}</h2>
							<div>
								<h3 class="product-price">NRs {{product.price}}</h3>
								<span class="product-available">{% if product.available %}In Stock{% endif %}</span>
							</div>
							<p>
                {{product.description}}
              </p>
               
							<div class="add-to-cart">
								<div class="qty-label">
									
								</div>
                <form action="{% url 'cart:cart_add' product.id %}" type="submit" method="post">
                  {{cart_product_form}}
								  <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                  {% csrf_token %}
                </form>
							</div>


							<ul class="product-links">
								<li>Category:</li>
								<li><a href="#">{{product.category}}</a></li>
								
							</ul>
							<ul class="product-links">
								<li>Share:</li>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="#"><i class="fa fa-envelope"></i></a></li>
							</ul>

						</div>
					</div>
    </div>
  </div>
  {% if recommended_products %}
    <div class="container">
      <!-- row -->
      <div class="row">

        <div class="col-md-12">
          <div class="section-title text-center">
            <h3 class="title">People also bought this</h3>
          </div>
        </div>
        <!-- product -->
        
          {% for p in recommended_products  %}
          <div class="col-md-3 col-xs-6">
            <div class="product">
              <div class="product-img">
                <img src="{{p.image.url}}" alt="{{p.name}}" width="100px" height="100px">
              </div>
              <div class="product-body">
                <p class="product-category">{{p.category}}</p>
                <h3 class="product-name"><a href="#">{{p.name}}</a></h3>
                <h4 class="product-price">NRs {{p.price}}</h4>
              </div>
            </div>
          </div>
          {% endfor %}
        <!-- /product -->
        {% endif %}
            
      </div>
    </div>
{% endblock content %}

{% comment %} {% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">NRs {{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form> 
    {{ product.description|linebreaks }}
    {% if recommended_products %}
      <div class="recommendations">
        <h3 People who bought this also bought></h3>
        {% for p  in recommended_products  %}
        <div class="item">
          <a href = "{{p.get_absolute_url}}">
            <img src = "{% if p.image %}{{p.image.url}}{% else %}{% static 'img/no_image.png' %}{% endif %}">
          </a>
          <p><a href="{{p.get_absolute_url}}">{{p.name}}</a></p>
        </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endblock %} {% endcomment %}

templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Products{% endblock title %}
{% block content %}
  <div class = "container">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- shop -->
					<div class="col-md-4 col-xs-6">
						<div class="shop">
							<div class="shop-img">
								<img src="{% static 'img/shop01.png' %}" alt="">
							</div>
							<div class="shop-body">
								<h3>Laptop<br>Collection</h3>
								<a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
							</div>
						</div>
					</div>
					<!-- /shop -->

					<!-- shop -->
					<div class="col-md-4 col-xs-6">
						<div class="shop">
							<div class="shop-img">
								<img src="{% static 'img/shop03.png' %}" alt="">
							</div>
							<div class="shop-body">
								<h3>Accessories<br>Collection</h3>
								<a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
							</div>
						</div>
					</div>
					<!-- /shop -->

					<!-- shop -->
					<div class="col-md-4 col-xs-6">
						<div class="shop">
							<div class="shop-img">
								<img src="{% static 'img/shop02.png' %}" alt="">
							</div>
							<div class="shop-body">
								<h3>Cameras<br>Collection</h3>
								<a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
							</div>
						</div>
					</div>
					<!-- /shop -->
				</div>
				<!-- /row -->
			</div>
  </div>
  <div class = "container">
    <div class = "row">
      	<!-- section title -->
					<div class="col-md-12">
						<div class="section-title">
							<h3 class="title">Our Products</h3>							
						</div>
					</div>
				<!-- /section title -->
        <!-- Products tab & slick -->
        <div class = "col-md-12">
          <div class = "row">
            <div class = "products-tab">
              <div id="tab1" class="tab-pane active">
                <div class="products-slick" data-nav="#slick-nav-1">
                  <!-- product -->               
                    {% for product in products %}
                    <div class = "product">
                      <div class="product-img">
                        <img src="{{product.image.url}}" alt="{{product.name}}">
                      </div>
							<div class="product-body">
								<p class="product-category">{{product.category}}</p>
									<h3 class="product-name"><a href="{{product.get_absolute_url}}">{{product.name}}</a></h3>
									<h4 class="product-price">NRs {{product.price}}</h4>
							</div>
							<div class="add-to-cart">
								<form action="{% url 'cart:cart_add_list' product.id %}">
									<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
								</form>
							</div>                     
                    </div>
                    {% endfor %}                         
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock content %}




























{% comment %} {% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %} class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        NRs {{ product.price }}
      </div>
    {% endfor %}
  </div>
{% endblock %} {% endcomment %}

templates/shop/product/search_results.html
{% extends 'shop/base.html' %}
{% block title %}Search{% endblock title %}

{% block content %}
    {% for p in result %}
        <img src = {{p.image.url}} width="100px" height="100px/>
        <p> {{p.name}} </p>
    {% endfor %}
{% endblock content %}

templates/shop/product/store.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
    		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					<div id="aside" class="col-md-3">
						<!-- aside Widget -->
						<div class="aside">
                            <h3 class="aside-title">Price</h3>
                            <form action="{% url 'shop:product_store' %}">
                                <div class="price-filter">
                                    <div id="price-slider"></div>
                                    <div class="input-number price-min">
                                        <input id="price_min" type="number" name="min_price">
                                        <span class="qty-up">+</span>
                                        <span class="qty-down">-</span>
                                    </div>
                                    <span>-</span>
                                    <div class="input-number price-max">
                                        <input id="price_max" type="number" name="max_price">
                                        <span class="qty-up">+</span>
                                        <span class="qty-down">-</span>
                                    </div>
                                </div>
                                <div class="add-to-cart">
                                        <button class="add-to-cart-btn" type="submit">Filter</button>         
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <!-- product -->
                         
                        {% for p in products %}
                            <div class="col-md-3 col-xs-6">
                                
                                <div class="product">
                                    <div class="product-img">
                                        <img src="{{p.image.url}}" alt="{{p.name}}">
                                    </div>
                                    <div class="product-body">
                                        <p class="product-category">{{p.category}}</p>
                                        <h3 class="product-name"><a href="{{p.get_absolute_url}}">{{p.name}}</a></h3>
                                        <h4 class="product-price">{{p.price}}</h4>
                                    </div>
                                    <div class="add-to-cart">
                                        <form action="{% url 'cart:cart_add_list' p.id %}">
                                            <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                                            
                                        </form>
                                    </div>
                                </div> 
                            </div>
                        {% endfor %} 
                        
                    
                    <!-- /product -->
                    </div>
                </div>
            </div>
        </div>
        
{% endblock content %}